spring:
   data:
        elasticsearch:
            cluster-name: es-5.0-test #默认为elasticsearch
            cluster-nodes: 127.0.0.1:9300 #配置es节点信息，逗号分隔，如果没有指定，则启动ClientNode
            properties:
                path:
                  logs: ./elasticsearch/log #elasticsearch日志存储目录
                  data: ./elasticsearch/data #elasticsearch数据存储目录
   activemq:
        broker-url: tcp://127.0.0.1:61616
        user: admin
        password: admin

queue: kmx.pas.job.sgtest